export const WEATHER_BASE_URL = process.env.REACT_APP_WEATHER_BASE_URL;
export const WEATHER_API_KEY = process.env.REACT_APP_WEATHER_API_KEY;

export const OPEN_WEATHER_BASE_URL =
  process.env.REACT_APP_OPEN_WEATHER_BASE_URL;
export const OPEN_WEATHER_API_KEY = process.env.REACT_APP_OPEN_WEATHER_API_KEY;
